[pytest]
pythonpath = .
testpaths = tests

markers =
    integration: mark a test as an integration test.
    unit: mark a test as a unit test.
    slow: mark a test as slow-running.
    db: mark a test that requires database access.

addopts = --cov=app --cov-report=term-missing

filterwarnings =
    ignore:'crypt' is deprecated and slated for removal in Python 3\.13:DeprecationWarning
    ignore:Accessing argon2\.__version__ is deprecated.*:DeprecationWarning
