"""add logo url and category model

Revision ID: 05ec263e9ef7
Revises: 44604f171707
Create Date: 2026-04-04 10:21:45.545785

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import uuid


# revision identifiers, used by Alembic.
revision: str = '05ec263e9ef7'
down_revision: Union[str, Sequence[str], None] = '44604f171707'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - adjusted for existing data ###
    op.create_table('categories',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )

    # Add as nullable first to avoid failing on existing rows.
    op.add_column('products', sa.Column('category_id', sa.UUID(), nullable=True))

    # Backfill existing products to a default category.
    default_category_id = str(uuid.uuid4())
    op.execute(
        sa.text(
            """
            INSERT INTO categories (id, name, description, is_active, created_at, updated_at)
            VALUES (:id, :name, :description, :is_active, NOW(), NULL)
            """
        ).bindparams(
            id=default_category_id,
            name="Uncategorized",
            description="Default category for existing products",
            is_active=True,
        )
    )
    op.execute(
        sa.text(
            """
            UPDATE products
            SET category_id = :category_id
            WHERE category_id IS NULL
            """
        ).bindparams(category_id=default_category_id)
    )

    op.alter_column('products', 'category_id', nullable=False)
    op.create_foreign_key(
        'fk_products_category_id_categories',
        'products',
        'categories',
        ['category_id'],
        ['id'],
    )
    op.add_column('supermarkets', sa.Column('logo_url', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('supermarkets', 'logo_url')
    op.drop_constraint('fk_products_category_id_categories', 'products', type_='foreignkey')
    op.drop_column('products', 'category_id')
    op.drop_table('categories')
    # ### end Alembic commands ###
