"""modified superm, prod, superm_prod

Revision ID: 44604f171707
Revises: af6c9c96215e
Create Date: 2026-03-29 18:48:24.500464

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '44604f171707'
down_revision: Union[str, Sequence[str], None] = 'af6c9c96215e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('supermarket_products', sa.Column('original_price', sa.Numeric(precision=10, scale=2), nullable=False))
    op.add_column('supermarket_products', sa.Column('discount_price', sa.Numeric(precision=10, scale=2), nullable=False))
    op.add_column('supermarket_products', sa.Column('expiration_date', sa.Date(), nullable=False))
    op.add_column('supermarket_products', sa.Column('stock_quantity', sa.Integer(), nullable=True))
    op.drop_constraint(op.f('uq_supermarket_product'), 'supermarket_products', type_='unique')
    op.create_unique_constraint('uq_supermarket_product_batch', 'supermarket_products', ['supermarket_id', 'product_id', 'expiration_date'])
    op.drop_column('supermarket_products', 'price')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('supermarket_products', sa.Column('price', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=False))
    op.drop_constraint('uq_supermarket_product_batch', 'supermarket_products', type_='unique')
    op.create_unique_constraint(op.f('uq_supermarket_product'), 'supermarket_products', ['supermarket_id', 'product_id'], postgresql_nulls_not_distinct=False)
    op.drop_column('supermarket_products', 'stock_quantity')
    op.drop_column('supermarket_products', 'expiration_date')
    op.drop_column('supermarket_products', 'discount_price')
    op.drop_column('supermarket_products', 'original_price')
    # ### end Alembic commands ###