"""add ShoppingCart

Revision ID: 97d35d05f272
Revises: 3d1bbf40d8c2
Create Date: 2026-04-25 08:24:10.534723

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '97d35d05f272'
down_revision: Union[str, Sequence[str], None] = '3d1bbf40d8c2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('shopping_cart',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('supermarket_product_id', sa.UUID(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('quantity > 0', name='ck_cart_quantity_positive'),
    sa.ForeignKeyConstraint(['supermarket_product_id'], ['supermarket_products.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'supermarket_product_id', name='uq_cart_user_supermarket_product')
    )
    op.create_index(op.f('ix_shopping_cart_supermarket_product_id'), 'shopping_cart', ['supermarket_product_id'], unique=False)
    op.create_index(op.f('ix_shopping_cart_user_id'), 'shopping_cart', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_shopping_cart_user_id'), table_name='shopping_cart')
    op.drop_index(op.f('ix_shopping_cart_supermarket_product_id'), table_name='shopping_cart')
    op.drop_table('shopping_cart')
    # ### end Alembic commands ###